Repository unicsmcr/hs_auth, pull requests merged in 2020-10, with the labels that each got.

#113 feat: Implement email verification for API v2
  authorization/v2/authorizer.go
  authorization/v2/authorizer_test.go
  config/base.yaml
  config/config.go
  config/development.yaml
  routers/api/v1/users.go
  routers/api/v1/users_test.go
  routers/api/v2/router.go
  routers/api/v2/router_test.go
  routers/api/v2/users.go
  routers/api/v2/users_test.go
  routers/frontend/routes.go
  routers/frontend/routes_test.go
  services/emailServiceV2.go
  services/mongo/userService.go
  services/mongo/userService_test.go
  services/sendgrid/emailService.go
  services/sendgrid/emailService_test.go
  services/sendgrid/v2/emailService.go
  services/sendgrid/v2/emailService_test.go
  services/userService.go
  wire.go
  wire_gen.go
Labels: auth-v2

#115 feat: Performance tests API v2
  .travis.yml
  Makefile
  authorization/v2/authorizer_test.go
  routers/api/v2/users_test.go
  testutils/testDB.go
Labels: auth-v2

#119 feat: Update GetPasswordResetEmail to use EmailService V2
  authorization/v2/authorizer.go
  authorization/v2/authorizer_test.go
  routers/api/v2/users.go
  routers/api/v2/users_test.go
  services/sendgrid/v2/emailService.go
  services/sendgrid/v2/emailService_test.go
Labels: auth-v2

#117 feat: Check user role and special permissions
  authorization/v2/authorizer.go
  authorization/v2/authorizer_test.go
  authorization/v2/common/uniformResourceIdentifier.go
  authorization/v2/common/uniformResourceIdentifier_test.go
  config/role/role.go
  config/role/role.yaml
  config/role/role_test.go
  routers/api/v2/router.go
  routers/api/v2/users_test.go
  wire_gen.go
Labels: auth-v2

#116 feat: Add Special Permissions API v2
  authorization/v2/common/uniformResourceIdentifier.go
  authorization/v2/common/uniformResourceIdentifier_test.go
  routers/api/v2/router.go
  routers/api/v2/router_test.go
  routers/api/v2/users.go
  routers/api/v2/users_test.go
  testutils/testutils.go
Labels: auth-v2

#122 feat: Migrate frontend Login to auth V2
  routers/frontend/router.go
  routers/frontend/router_test.go
  routers/frontend/routes.go
  routers/frontend/routes_test.go
  wire_gen.go
Labels: auth-v2

#124 feat: Implement RouterResource interface on frontend router
  routers/frontend/router.go
  routers/frontend/router_test.go
Labels: auth-v2

#125 feat: Migrate frontend Register to auth V2
  go.mod
  go.sum
  routers/api/v2/router.go
  routers/api/v2/router_test.go
  routers/api/v2/users.go
  routers/common/common.go
  routers/common/common_test.go
  routers/frontend/router.go
  routers/frontend/router_test.go
  routers/frontend/routes.go
  routers/frontend/routes_test.go
  wire_gen.go
Labels: auth-v2

#126 feat: Migrate frontend ForgotPassword to auth v2
  routers/frontend/routes.go
  routers/frontend/routes_test.go
Labels: auth-v2

#102 feat: Implement Get Authorized URIs
  authorization/v2/authorizer.go
  authorization/v2/common/uniformResourceIdentifier.go
  authorization/v2/common/uniformResourceIdentifier_test.go
  routers/api/v2/router.go
  routers/api/v2/tokens.go
  routers/api/v2/tokens_test.go
  testutils/testutils.go
Labels: auth-v2

#129 feat: Migrate frontend password reset to auth v2
  authorization/v2/authorizer.go
  authorization/v2/common/uniformResourceIdentifier.go
  authorization/v2/common/uniformResourceIdentifier_test.go
  routers/common/common.go
  routers/common/common_test.go
  routers/frontend/router.go
  routers/frontend/router_test.go
  routers/frontend/routes.go
  routers/frontend/routes_test.go
  services/sendgrid/v2/emailService.go
  templates/pages/resetPassword.gohtml
Labels: auth-v2

#131 feat: Migrate frontend email verification to auth V2
  config/role/role.yaml
  routers/frontend/router.go
  routers/frontend/router_test.go
  routers/frontend/routes.go
  routers/frontend/routes_test.go
  services/sendgrid/v2/emailService.go
Labels: auth-v2

#132 feat: Migrate frontend rendering to auth v2
  authorization/v2/authorizer.go
  authorization/v2/authorizer_test.go
  config/base.yaml
  config/config.go
  config/role/role.yaml
  routers/frontend/dataModels.go
  routers/frontend/frontendComponents.go
  routers/frontend/frontendComponents_test.go
  routers/frontend/pages.go
  routers/frontend/pages_test.go
  routers/frontend/router.go
  routers/frontend/router_test.go
  routers/frontend/routes.go
  routers/frontend/routes_test.go
  static/js/admin.js
  templates/pages/emailNotVerified.gohtml
  templates/pages/emailVerifyResend.gohtml
  templates/pages/forgotPassword.gohtml
  templates/pages/forgotPasswordEnd.gohtml
  templates/pages/login.gohtml
  templates/pages/profile.gohtml
  templates/pages/register.gohtml
  templates/pages/registerEnd.gohtml
  templates/pages/resetPassword.gohtml
  templates/pages/resetPasswordEnd.gohtml
  templates/pages/verificationTokenInvalid.gohtml
  templates/pages/verifyEmail.gohtml
  templates/partials/navbar.gohtml
  templates/partials/personalInformation.gohtml
  templates/partials/teamPanel.gohtml
  templates/partials/usersList.gohtml
Labels: auth-v2

#133 feat: Migrate frontend team management to auth v2
  authorization/v2/common/uniformResourceIdentifier.go
  authorization/v2/common/uniformResourceIdentifier_test.go
  config/role/role.yaml
  routers/frontend/router.go
  routers/frontend/router_test.go
  routers/frontend/routes.go
  routers/frontend/routes_test.go
Labels: auth-v2

#135 feat: Migrate frontend admin management to auth v2
  config/role/role.go
  config/role/role.yaml
  config/role/role_test.go
  routers/frontend/pages.go
  routers/frontend/router.go
  routers/frontend/router_test.go
  routers/frontend/routes.go
  services/userService.go
  static/js/admin.js
  templates/pages/emailNotVerified.gohtml
Labels: auth-v2

#137 feat: Remove auth system v1
  config/base.yaml
  config/config.go
  config/config_test.go
  config/development.yaml
  entities/user.go
  entities/user_test.go
  routers/api/v1/router.go
  routers/api/v1/router_test.go
  routers/api/v1/teams.go
  routers/api/v1/teams_test.go
  routers/api/v1/types.go
  routers/api/v1/users.go
  routers/api/v1/users_test.go
  routers/api/v2/teams_test.go
  routers/api/v2/tokens_test.go
  routers/api/v2/users.go
  routers/api/v2/users_test.go
  routers/frontend/frontendComponents_test.go
  routers/frontend/router.go
  routers/frontend/router_test.go
  routers/frontend/routes.go
  routers/frontend/routes_test.go
  routers/router.go
  routers/router_test.go
  services/emailService.go
  services/mongo/teamService.go
  services/mongo/teamService_test.go
  services/mongo/userService.go
  services/mongo/userService_test.go
  services/sendgrid/emailService.go
  services/sendgrid/emailService_test.go
  services/teamService.go
  services/userService.go
  utils/auth/auth.go
  utils/auth/auth_test.go
  utils/auth/common/authLevel.go
  utils/auth/common/authLevel_test.go
  utils/encryption.go
  utils/encryption_test.go
  wire.go
  wire_gen.go
Labels: auth-v2

#139 feat: Review role permissions
  config/role/role.yaml
  routers/api/v2/router.go
Labels: auth-v2

#141 feat: Implement SMTP email service client
  app.env.example
  config/base.yaml
  config/config.go
  config/development.yaml
  environment/environment.go
  environment/environment_test.go
  services/multiplexers/multiplexers.go
  services/multiplexers/multiplexers_test.go
  services/multiplexers/types/types.go
  services/smtp/smtpEmailService.go
  services/smtp/smtpEmailService_test.go
  services/smtp/testEmailTemplate.txt
  utils/smtp.go
  wire.go
  wire_gen.go
Labels: technical-debt

#147 fix: ReturnTo in navbar displayed when ReturnTo cookie is invalid
  routers/frontend/routes.go
  templates/partials/navbar.gohtml
Labels: bug

#149 fix: Links in emails are rendered as plaintext
  templates/emails/emailVerify_email.gohtml
  templates/emails/passwordReset_email.gohtml
Labels: bug

#148 feat: Add hs_apply URIs for each role
  config/role/role.yaml
Labels: auth-v2

#150 feat: Migrate back to GH actions
  .github/workflows/benchmarks.yml
  .github/workflows/tests.yml
  .travis.yml
Labels: technical-debt

#153 feat: Add GUH2020 logo to email templates
  templates/emails/emailVerify_email.gohtml
  templates/emails/passwordReset_email.gohtml
Labels: mvp
