Repository unicsmcr/hs_auth, pull requests merged in 2020-11, with the labels that each got.

#155 feat: add navbar uri for hs_apply frontend to role config
  config/role/role.yaml
Labels: auth-v2

#158 fix: Replace null response from GetAuthorizedResources with empty array
  routers/api/v2/tokens.go
  routers/api/v2/tokens_test.go
Labels: bug

#160 feat: Add permissions for hs_hub users
  config/role/role.yaml
Labels: mvp
